import type { TriageResult, UrgencyLevel } from "@/lib/triage-data"

interface ReportInput {
  id?: string
  date?: string
  age?: string
  gender?: string
  duration?: string
  symptoms: string[]
  result: TriageResult
}

const URGENCY_COLOR: Record<UrgencyLevel, string> = {
  Low: "#16a34a",
  Moderate: "#d97706",
  High: "#ea580c",
  Emergency: "#dc2626",
}

// Builds a printable doctor-ready summary and opens the browser print dialog
// (the user can save it as a PDF). Dependency-free PDF generation.
export function downloadReport(input: ReportInput) {
  const { symptoms, result } = input
  const date = input.date ?? new Date().toISOString().slice(0, 10)
  const id = input.id ?? "cons_" + Math.random().toString(36).slice(2, 8)

  const predictionsHtml = result.predictions
    .map(
      (p) => `
        <tr>
          <td>${p.disease}</td>
          <td>${Math.round(p.confidence * 100)}%</td>
          <td>${p.matchedSymptoms.join(", ") || "-"}</td>
        </tr>`,
    )
    .join("")

  const precautionsHtml = result.precautions.map((p) => `<li>${p}</li>`).join("")
  const testsHtml = result.recommendedTests.map((t) => `<li>${t}</li>`).join("")

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Consultation Report ${id}</title>
  <style>
    * { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; }
    body { color: #0f172a; max-width: 720px; margin: 40px auto; padding: 0 24px; line-height: 1.5; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    h2 { font-size: 15px; text-transform: uppercase; letter-spacing: .05em; color: #64748b; margin-top: 28px; }
    .meta { color: #64748b; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 14px; }
    th, td { text-align: left; padding: 8px 6px; border-bottom: 1px solid #e2e8f0; }
    th { color: #64748b; font-size: 12px; text-transform: uppercase; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; color: #fff; font-weight: 600; font-size: 13px; }
    ul { margin: 8px 0; padding-left: 20px; }
    .disclaimer { margin-top: 32px; padding: 12px 16px; background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; font-size: 12px; color: #92400e; }
    .chips span { display: inline-block; background: #e2e8f0; border-radius: 999px; padding: 3px 10px; font-size: 13px; margin: 2px 4px 2px 0; }
  </style>
</head>
<body>
  <h1>AI Health Triage Assistant</h1>
  <div class="meta">Doctor-Ready Consultation Summary &middot; ${id} &middot; ${date}</div>

  <h2>Patient Intake</h2>
  <div class="meta">
    Age: ${input.age || "N/A"} &nbsp;|&nbsp; Gender: ${input.gender || "N/A"} &nbsp;|&nbsp; Duration: ${input.duration || "N/A"}
  </div>

  <h2>Reported Symptoms</h2>
  <div class="chips">${symptoms.map((s) => `<span>${s}</span>`).join("")}</div>

  <h2>Urgency</h2>
  <span class="badge" style="background:${URGENCY_COLOR[result.urgency]}">${result.urgency}</span>

  <h2>Predicted Conditions (ML model)</h2>
  <table>
    <thead><tr><th>Condition</th><th>Confidence</th><th>Matched symptoms</th></tr></thead>
    <tbody>${predictionsHtml}</tbody>
  </table>

  <h2>Explanation (LLM)</h2>
  <p>${result.explanation}</p>

  <h2>Precautions</h2>
  <ul>${precautionsHtml}</ul>

  <h2>Recommended Tests</h2>
  <ul>${testsHtml}</ul>

  <div class="disclaimer">
    This report is generated by a triage and decision-support tool. It does not replace professional medical
    diagnosis. The ML model predicts likely conditions and the LLM only explains them. Please consult a qualified
    doctor for confirmation and treatment.
  </div>

  <script>window.onload = function () { window.print(); }</script>
</body>
</html>`

  const win = window.open("", "_blank")
  if (win) {
    win.document.open()
    win.document.write(html)
    win.document.close()
  }
}
